// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeyTsODnNRAjQLXO9z-TlAmWXd_UJ4NIc',
    appId: '1:676216601192:web:a4e0876f96fd7566ec19dd',
    messagingSenderId: '676216601192',
    projectId: 'to-do-list-app-c7fad',
    authDomain: 'to-do-list-app-c7fad.firebaseapp.com',
    storageBucket: 'to-do-list-app-c7fad.appspot.com',
    measurementId: 'G-C7816T0NWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBICaW72DqjkPx458Anr42HycVKKDnse9M',
    appId: '1:676216601192:android:c802a05fb696e2a8ec19dd',
    messagingSenderId: '676216601192',
    projectId: 'to-do-list-app-c7fad',
    storageBucket: 'to-do-list-app-c7fad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRdKH9dyRnfovwI276RCxvJbvkVW3WPj4',
    appId: '1:676216601192:ios:592d5a624f6b4516ec19dd',
    messagingSenderId: '676216601192',
    projectId: 'to-do-list-app-c7fad',
    storageBucket: 'to-do-list-app-c7fad.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRdKH9dyRnfovwI276RCxvJbvkVW3WPj4',
    appId: '1:676216601192:ios:592d5a624f6b4516ec19dd',
    messagingSenderId: '676216601192',
    projectId: 'to-do-list-app-c7fad',
    storageBucket: 'to-do-list-app-c7fad.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeyTsODnNRAjQLXO9z-TlAmWXd_UJ4NIc',
    appId: '1:676216601192:web:59ec491013aca75fec19dd',
    messagingSenderId: '676216601192',
    projectId: 'to-do-list-app-c7fad',
    authDomain: 'to-do-list-app-c7fad.firebaseapp.com',
    storageBucket: 'to-do-list-app-c7fad.appspot.com',
    measurementId: 'G-NV4B33H8WR',
  );
}
